# Generated by Django 3.1.12 on 2025-12-09 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Destino')),
                ('descripcion', models.TextField(help_text='Descripción detallada del destino', verbose_name='Descripción')),
                ('capacidad_maxima', models.PositiveIntegerField(default=50, help_text='Número máximo de visitantes por día', verbose_name='Capacidad Máxima')),
                ('precio_entrada', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Precio de Entrada')),
                ('horario_apertura', models.TimeField(blank=True, null=True, verbose_name='Horario de Apertura')),
                ('horario_cierre', models.TimeField(blank=True, null=True, verbose_name='Horario de Cierre')),
                ('activo', models.BooleanField(default=True, verbose_name='Destino Activo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='destinos/', verbose_name='Imagen del Destino')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Destino Turístico',
                'verbose_name_plural': 'Destinos Turísticos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('total_reservaciones', models.PositiveIntegerField(default=0, verbose_name='Total de Reservaciones')),
                ('total_visitantes', models.PositiveIntegerField(default=0, verbose_name='Total de Visitantes')),
                ('destino_mas_popular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Destino Más Popular')),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del cliente', max_length=200, verbose_name='Nombre Completo')),
                ('email', models.EmailField(help_text='Dirección de correo electrónico del cliente', max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(help_text='Número telefónico de 10 dígitos', max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos', regex='^\\d{10}$')], verbose_name='Teléfono')),
                ('destino', models.CharField(choices=[('zona_arqueologica', 'Zona Arqueológica'), ('parque_soraya', 'Parque Soraya Jiménez'), ('santa_marta', 'Santa Marta'), ('parroquia_divino', 'Parroquia Divino Salvador'), ('volcan_caldera', 'Volcán de la Caldera'), ('parque_ciencia', 'Parque de la Ciencia')], help_text='Lugar a visitar', max_length=50, verbose_name='Destino Turístico')),
                ('fecha_visita', models.DateField(help_text='Fecha programada para la visita', verbose_name='Fecha de Visita')),
                ('numero_personas', models.PositiveIntegerField(help_text='Cantidad de personas (1-50)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Número de Personas')),
                ('comentarios', models.TextField(blank=True, help_text='Información adicional o solicitudes especiales', null=True, verbose_name='Comentarios')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado de Reservación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la reservación está activa', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='reservacion',
            index=models.Index(fields=['fecha_visita', 'destino'], name='contacto_re_fecha_v_c1155e_idx'),
        ),
        migrations.AddIndex(
            model_name='reservacion',
            index=models.Index(fields=['email'], name='contacto_re_email_ab045c_idx'),
        ),
        migrations.AddIndex(
            model_name='reservacion',
            index=models.Index(fields=['estado'], name='contacto_re_estado_6f0dfc_idx'),
        ),
    ]
